_wandb:
    value:
        cli_version: 0.19.4
        code_path: code/normallearning.py
        m: []
        python_version: 3.11.9
        t:
            "1":
                - 1
                - 11
                - 41
                - 49
                - 51
                - 55
            "2":
                - 1
                - 11
                - 41
                - 49
                - 51
                - 55
            "3":
                - 3
                - 23
                - 55
            "4": 3.11.9
            "5": 0.19.4
            "6": 4.45.0.dev0
            "8":
                - 3
                - 5
            "12": 0.19.4
            "13": windows-amd64
